### ISSUE TITLE
requirements not included/cookie file doesn't include language

### ISSUE THREAD

**Issue by Jakob1223** [leon-wm/TikTok-Autobot#4]
Some imported requirements aren't included in `requirements.txt`
The cookie for the language isn't set!

**Comment by Jakob1223** [comment]
Here are the files:
[requirements.txt](https://github.com/leon-wm/TikTok-Autobot/files/13193137/requirements.txt)
[README.md](https://github.com/leon-wm/TikTok-Autobot/files/13193143/README.md)

**Comment by leon-wm** [comment]
#5

**Comment by leon-wm** [comment]
#5
